import "./globals.css";

export const metadata = {
  title: "Nabeghe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body className="font-Yekan" suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}